apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nvfm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-nvfm@sha256:a818e5d0953aca1adffcd5a229cd4786ffe0da85a3cc0c65c44b7b5fc30b6b71
        name: my-nodejs
        resources: {}
status: {}
